name: CI

on:
  push:
  pull_request:

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.12.0'

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.12.0'

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci

      # run: npm test när tester kommer på plats
      